Phase 11
Star-Academy/Summer1400-SE-Team20 pull request #10
Opened 2021-08-16 13:32 UTC by mtndaghyani

2021-08-20 20:07 UTC, nazari02105 commented on Phase-5/SearchWebAPI/Controllers/SearchController.cs
> +using SearchEngine.Interfaces.Core;
I Actually really love this comment:
useless imports :)))))) (just kidding)
it is not really important but it is good to remove useless imports

2021-08-20 20:07 UTC, nazari02105 commented on Phase-5/SearchWebAPI/Controllers/SearchController.cs
> +        public List<int> Query(string toSearch)
IDE give this fact about this HttpGet():
Parentheses are redundant if attribute has no arguments

2021-08-20 20:08 UTC, nazari02105 commented on Phase-5/SearchWebAPI/Program.cs
> +using Microsoft.Extensions.Logging;
ahhh Here you go again :)

2021-08-20 20:09 UTC, nazari02105 requested changes
some tiny comments

2021-08-22 06:32 UTC, nazari02105 approved these changes

2021-08-22 08:37 UTC, nazari02105 approved these changes
Well Done

2021-08-24 05:53 UTC, mohammad258852 approved these changes

2021-08-25 04:33 UTC, alrz1999 approved these changes

2021-08-25 05:49 UTC, merged