Review codes and remove bad smells
Star-Academy/Summer1400-SE-Team20 pull request #4
Opened 2021-07-27 07:59 UTC by mtndaghyani

2021-07-27 08:21 UTC, mohammad258852 approved these changes
fine

2021-07-27 08:59 UTC, mohammad258852 approved these changes

2021-07-27 12:36 UTC, mhgheisarieh commented on Phase-1/src/main/java/Main.java
>      }
خوبه برای این برای این بخش که داره کارهای اولیه رو میکنه و کوئری ها رو دریافت میکنه و داره میزنه یک آبجکت منیجر ایجاد کنید. 

که اون این کارها رو انجام بده.

2021-07-27 12:36 UTC, mhgheisarieh commented on Phase-1/src/main/java/SearchEngine.java
> +        Pattern pattern = Pattern.compile("([,.;'\"?!@#$%^&:*]*)([+-]?\\w+)([,.;'\"?!@#$%^&:*]*)");
خوبه اینو به صورت یک ثابت تعریف کنین

2021-07-27 12:36 UTC, mhgheisarieh commented on Phase-1/src/main/java/SearchEngine.java
> +    }
نمیدونم فور به همراه شرط رو میشه به صورت lambda expression نوشت یا نه
اگر بشه نوشت اولویت داره. 


هم این جا هم دو سه جا دیگه تو این فایل ...

2021-07-27 16:56 UTC, nazari02105 approved these changes

2021-07-28 05:15 UTC, mtndaghyani commented on Phase-1/src/main/java/Main.java
>      }
کلاس منیجر اضافه و پیاده سازی شد

2021-07-28 05:16 UTC, mtndaghyani commented on Phase-1/src/main/java/SearchEngine.java
> +        Pattern pattern = Pattern.compile("([,.;'\"?!@#$%^&:*]*)([+-]?\\w+)([,.;'\"?!@#$%^&:*]*)");
یک ثابت تعریف شد

2021-07-28 05:16 UTC, mtndaghyani commented on Phase-1/src/main/java/SearchEngine.java
> +    }
به جای فور از لامبدا استفاده کردیم.

2021-07-28 05:18 UTC, mtndaghyani reviewed
تغییرات اشاره شده اعمال شدند لطفا بازبینی کنید.
@mhgheisarieh

2021-07-31 05:29 UTC, alrz1999 requested changes

2021-07-31 05:29 UTC, alrz1999 commented on Phase-1/src/main/java/InvertedIndex.java
> +        this.fileReader =  reader;
به نظرم 
InvertedIndex
نیازی نداره بدونه
FileReader
 چیه و فقط محتوایی که قراره ایندکس کنه باید بهش داده بشه

2021-07-31 07:29 UTC, mtndaghyani commented on Phase-1/src/main/java/InvertedIndex.java
> +        this.fileReader =  reader;
همان طور که در جلسه صحبت شد، این روش هم مناسب است
با تشکر

2021-07-31 07:44 UTC, alrz1999 approved these changes

2021-07-31 12:27 UTC, mhgheisarieh approved these changes

2021-07-31 13:03 UTC, merged