Feature/unit test
Star-Academy/Summer1400-SE-Team20 pull request #5
Opened 2021-07-28 13:02 UTC by mtndaghyani

Add unit tests to our project

2021-08-01 07:38 UTC, nazari02105 commented on Phase-1/src/main/java/SearchEngine.java
> +}
سلام. حقیقتش این بخش به فاز ۳ مربوط نمیشود ولی لازم دانستیم که بگیم. این بخش باگ کوچکی دارد به این شکل که شما محتویات یک فایل را قرار بدهید ای(حرف اول انگلیسی) و سی و محتویات فایل دوم را قرار بدهید بی و سی با فاصله بین هر حرف در ۲ فایل. حال اگر کاربر ورودی را بدهد ای(حرف اول انگلیسی) بی و سی با یک فاصله بین هر کدام، درست این است که هیچی برنگرداند چون هیچ فایلی شامل این ترکیب نیست ولی هر دو فایل برگردانده میشود به عنوان جواب
لطفا بررسی شود

2021-08-01 07:42 UTC, nazari02105 commented on Phase-1/src/test/java/FileReaderTests.java
> +}
در کل در بحث تست ها ما کاوریج ۵۳ درصد گرفتیم که خب البته برای کلاس استمر است که بهتر بود یا اکسکلود میکردید یابه نوعی کاوریج را پوشش میداد.
در مورد این کلاس، برای من تست پاس شد ولی برای محمد که سیستم عامل لینوکس دارد، فیل شد تست که البته فکر کنم به خاطر نوع آدرس دهی و ترتیب خواندن تست ها در این سیستم عامل است و خیلی نمی شود به عنوان اشتباه شما این موضوع را تلقی کرد و فقط این موضوع را مطرح کردیم که اگر راهی وجود داشت برای این موضوع و دوست داشتید، بررسی کنید

2021-08-01 07:46 UTC, nazari02105 commented on Phase-1/src/test/java/ManagerTest.java
> +    private final Manager manager = new Manager(DATASET_PATH);
در این مورد به نظر ما بهتر بود که از فایل تستی که در همون فولدر تست گذاشتید استفاده می کردید و از فایل های اصلی استفاده نمی کردید. درست است که ماک کردید ولی برخی تست های این بخش عمل ماک را انجام نداده اید. باز هم درست است که در آن تست ها خیلی با خود فایل ها کاری نداشته اید و احتمال آسیب دیدن فایل ها خیلی خیلی کم است ولی در بدترین حالت، ممکن است که کلاس اصلی دارای مشکلی باشد و به وسیله ی آن باگ، فایل ها آسیب ببینند و در کل در بهتر است یا کلا با فایل های نمونه در فپلدر تست کار کنید و یا عمل ماک کردن را برای همه تست ها حتی آن هایی که تماس مستقیم با فایل ها ندارندهم اعمال کنید

2021-08-01 07:47 UTC, nazari02105 commented on Phase-1/src/test/java/ManagerTest.java
> +    private final Manager manager = new Manager(DATASET_PATH);
در این مورد به نظر ما بهتر بود که از فایل تستی که در همون فولدر تست گذاشتید استفاده می کردید و از فایل های اصلی استفاده نمی کردید. درست است که ماک کردید ولی برخی تست های این بخش عمل ماک را انجام نداده اید. باز هم درست است که در آن تست ها خیلی با خود فایل ها کاری نداشته اید و احتمال آسیب دیدن فایل ها خیلی خیلی کم است ولی در بدترین حالت، ممکن است که کلاس اصلی دارای مشکلی باشد و به وسیله ی آن باگ، فایل ها آسیب ببینند و در کل در بهتر است یا کلا با فایل های نمونه در فپلدر تست کار کنید و یا عمل ماک کردن را برای همه تست ها حتی آن هایی که تماس مستقیم با فایل ها ندارندهم اعمال کنید

2021-08-01 07:54 UTC, nazari02105 requested changes
لطفا موارد گفته شده بررسی شود

2021-08-01 12:36 UTC, soroushtaslimi commented on Phase-1/src/main/java/SearchEngine.java
> +}
Thanks. We corrected this part.

2021-08-02 05:36 UTC, mtndaghyani commented on Phase-1/src/test/java/ManagerTest.java
> +    private final Manager manager = new Manager(DATASET_PATH);
این مورد اصلاح شد

2021-08-02 06:30 UTC, mtndaghyani commented on Phase-1/src/test/java/FileReaderTests.java
> +}
در مورد بحث کاوریج اگر استمر را در تنظیمات اکسکلود کنید کاوریج 95 حاصل می شود
مورد مسیردهی اصلاح شد

2021-08-02 06:42 UTC, soroushtaslimi approved these changes

2021-08-02 06:57 UTC, mohammad258852 approved these changes
مشکلات رفع شده بود.
فقط درمورد تستی که فیل شده بود. مشکلش اون ادرس دهی نبود و اگه خواستید اون رو برگردونید.
مشکلش این بود که ترتیب خوندن فایلا فرق داشت و دوتا ارایه‌ای که مقایسه میکردید مثل هم بودن ولی با ترتیب مختلف.
توی داک جاوا هم نوشته بود که listFiles ترتیبی رو تضمین نمیکنه
به هرحال فکر نمیکنم خیلی مشکل جدی باشه

2021-08-02 07:37 UTC, nazari02105 approved these changes
موارد حل شده بود. موفق باشید

2021-08-03 05:48 UTC, alrz1999 approved these changes

2021-08-03 05:48 UTC, alrz1999 commented on Phase-1/src/test/java/ManagerTest.java
> +    public void testFinished_WHEN_dollarSign_EXPECT_true(){
تو جاوا بهتره اسم توابع
camelCase
باشه

2021-08-03 07:04 UTC, mhgheisarieh approved these changes

2021-08-03 07:25 UTC, merged