Phase 4
Star-Academy/Summer1400-SE-Team20 pull request #6
Opened 2021-08-03 05:40 UTC by soroushtaslimi

output Top Students

2021-08-03 11:09 UTC, nazari02105 commented on Phase-4/education/Program.cs
> +using System.Linq;
یوزینگ های بدون استفاده بهتر است حذف شود

2021-08-03 11:10 UTC, nazari02105 commented on Phase-4/education/Program.cs
> +    }
در این تمرین درست است که خیلی تمرین کوچکی است ولی باز بهتر بود کلاس ها در فایل های جدا باشند

2021-08-03 11:13 UTC, nazari02105 commented on Phase-4/education/Program.cs
> +
در یکی از لینک هایی که در داک فاز ۴ گذاشته شده بود، عنوان شده بود که بهتر است اسم فیلد های
Read Only
مخفف نباشد

2021-08-03 11:14 UTC, nazari02105 commented on Phase-4/education/Program.cs
> +            Console.WriteLine(System.IO.Directory.GetCurrentDirectory());
ما کاربرد این خط ۳۶ را متوجه نشدیم و حدسمان این بود برای دیباگ گذاشتید و یادتان رفته بردارید
اگر اینگونه است بهتر است برداشته شود وگرنه یک کامنت در مورد کارایی آن گذاشته شود

2021-08-03 11:15 UTC, nazari02105 requested changes
لطفا موارد گفته شده بررسی شود

2021-08-05 08:53 UTC, mohammad258852 approved these changes

2021-08-05 16:00 UTC, nazari02105 approved these changes
موارد برطرف شده بود

2021-08-05 18:24 UTC, alrz1999 requested changes
Update gitignore

2021-08-05 18:24 UTC, alrz1999 commented on Phase-4/education/Program.cs
> +        private static void Main(string[] args)
Long Method🙂
Single Responsibility

2021-08-07 09:46 UTC, mhgheisarieh approved these changes

2021-08-08 11:39 UTC, alrz1999 approved these changes

2021-08-08 14:00 UTC, merged