Phase 8
Star-Academy/Summer1400-SE-Team20 pull request #9
Opened 2021-08-14 14:37 UTC by mtndaghyani

2021-08-15 08:23 UTC, nazari02105 commented on Phase-5/SearchEngine/Classes/Core/SearchEngineCore.cs
> +        }
این موضوع را به عنوان اسمل در جایی پیدا نکردیم ولی فکر کنم کانستراکتور قبل از متدها بیاید بهتر باشد ولی در کل خیلی موضوع با اهمیتی نیست

2021-08-15 08:25 UTC, nazari02105 commented on Phase-5/SearchEngineTests/Database/DatabaseContextTests.cs
> +        }
این کامنت 
ToDo
اگر باید کاری انجام دهید بهتر است قبل پوش کردن انجام دهید چون خود رایدر هم به این موضوع واکنش نشان می دهد
ولی اگر کاری دیگر لازم نیست انجام بدهید، بهتر است پاک شود

2021-08-15 08:25 UTC, nazari02105 commented on Phase-5/SearchEngineTests/Database/DatabaseInvertedIndexTests.cs
> +}
دلیل وجود این کلاس را متوجه نمی شوم

2021-08-15 08:27 UTC, nazari02105 requested changes
لطفا موارد گفته شده بررسی شود

2021-08-15 12:17 UTC, mohammad258852 requested changes
عملکرد
DatabaseInvertedIndex
تست نشده بود. می‌توان از
InMemory
استفاده کرد

2021-08-15 12:17 UTC, mohammad258852 commented on Phase-5/SearchEngine/Classes/Indexers/DatabaseInvertedIndex.cs
> +            IndexingContext.SaveChanges();
اینجا و در تابع قبل چیزی از دیتابیس تغییر نکرده و فقط اطلاعات رو خوندید.
نیازه که
SaveChanges
صدا زده بشه

2021-08-15 12:17 UTC, mohammad258852 commented on Phase-5/SearchEngine/Classes/Indexers/WordProcessor.cs
> +        private readonly string _pattern = "([,.;'\"?!@#$%^&:*]*)(\\w+)([,.;'\"?!@#$%^&:*]*)";
میتواند به عنوان یک ثابت ذخیره شود

2021-08-15 12:17 UTC, mohammad258852 commented on Phase-5/SearchEngine/Classes/Config.cs
> +        public string ConnectionString { get; set; }
از این متغیر استفاده نشده و در 
IndexingContex
 مقدار آن هاردکد شده است

2021-08-15 12:17 UTC, mohammad258852 commented on Phase-5/SearchEngine/Classes/Manager.cs
> +        private void MakeInvertedIndex(bool doIndex)
پارامتر ورودی در
_config
هست و در همین تابع از
_config
استفاده شده

2021-08-15 12:17 UTC, mohammad258852 commented on Phase-5/SearchEngine/Classes/IO/Database/IndexingContext.cs
> +                .HasForeignKey(x => x.WordId);
درمورد رابطه کلمه و داک و کلاس
Word_Document
اگر در کلاس کلمه لیستی از داک‌ها و در کلاس داک لیستی از کلمات باشد به طور خود کار رابطه آن‌ها چند به چند می‌شود و 
ef core
جدول مربوطه رو خودکار درست میکند و نیازی به استفاده از کلاس کلمه-داک نیست

2021-08-16 12:10 UTC, mtndaghyani commented on Phase-5/SearchEngine/Classes/IO/Database/IndexingContext.cs
> +                .HasForeignKey(x => x.WordId);
این روش هم در داکیومنت رسمی مایکروسافت مورد تایید قرار گرفته است و این امکان را می دهد که بتوان دقیق تر دیتابیس را مدل کرد. ضمن اینکه دیتابیس ممکن است از قبل آماده باشد و هم چنین اینگونه می توان به کلاس میانی دسترسی داشت.
[به اینجامراجعه کنید](https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#indirect-many-to-many-relationships)

2021-08-17 05:26 UTC, nazari02105 approved these changes

2021-08-17 10:42 UTC, mohammad258852 approved these changes

2021-08-21 12:45 UTC, alrz1999 commented on Phase-5/SearchEngine/Classes/IO/Database/Models/Word_Document.cs
> +    public class Word_Document
https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md

2021-08-21 12:45 UTC, alrz1999 commented on Phase-5/SearchEngine/Classes/Indexers/Indexer.cs
> +            Console.Error.WriteLine("Index end");
چرا
Console.Error?

2021-08-21 13:52 UTC, soroushtaslimi commented on Phase-5/SearchEngine/Classes/Indexers/Indexer.cs
> +            Console.Error.WriteLine("Index end");
Cosole.Error
معادل
stderr
است که برای نوشتن لاگ های غیرضروری کاربرد دارد.

2021-08-21 14:39 UTC, soroushtaslimi approved these changes

2021-08-21 14:46 UTC, alrz1999 approved these changes

2021-08-22 05:07 UTC, merged